const TOTAL_BOXES = 256
const COLOR_START = '#395fab'
const COLOR_END = '#44ae52'
const TRANSITION_DELAY_WELCOME = 3000
const CLICK_AMOUT = 35

export { TOTAL_BOXES, COLOR_START, COLOR_END, TRANSITION_DELAY_WELCOME, CLICK_AMOUT }
